import type { Pokemon, PokemonType } from "./types";

export const ALL_POKEMON_TYPES: PokemonType[] = [
  "Normal", "Fire", "Water", "Grass", "Electric", "Ice", "Fighting", "Poison",
  "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark",
  "Steel", "Fairy"
];

export const allPokemon: Pokemon[] = [
  {
    id: 1,
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    stats: [
      { name: "HP", value: 45 },
      { name: "Attack", value: 49 },
      { name: "Defense", value: 49 },
      { name: "Sp. Atk", value: 65 },
      { name: "Sp. Def", value: 65 },
      { name: "Speed", value: 45 },
    ],
    description: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    abilities: ["Overgrow", "Chlorophyll"],
    appearance: "Found in sunny grasslands and forests. It is often one of the first Pokémon given to new trainers in the Kanto region.",
    diet: "It absorbs nutrients from the seed on its back, but also eats small insects and berries.",
    image2d: "bulbasaur",
    evolutions: [{ id: 2, name: "Ivysaur" }],
  },
  {
    id: 2,
    name: "Ivysaur",
    types: ["Grass", "Poison"],
    stats: [
        { name: "HP", value: 60 },
        { name: "Attack", value: 62 },
        { name: "Defense", value: 63 },
        { name: "Sp. Atk", value: 80 },
        { name: "Sp. Def", value: 80 },
        { name: "Speed", value: 60 },
    ],
    description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
    abilities: ["Overgrow", "Chlorophyll"],
    appearance: "The bulb on its back blossoms when it absorbs enough nutrition. The bulb gives off a sweet scent.",
    diet: "Like Bulbasaur, it primarily gets energy from its bulb, but will supplement with bugs.",
    image2d: "ivysaur",
    previousEvolution: { id: 1, name: "Bulbasaur" },
    evolutions: [{ id: 3, name: "Venusaur" }],
  },
  {
    id: 3,
    name: "Venusaur",
    types: ["Grass", "Poison"],
    stats: [
        { name: "HP", value: 80 },
        { name: "Attack", value: 82 },
        { name: "Defense", value: 83 },
        { name: "Sp. Atk", value: 100 },
        { name: "Sp. Def", value: 100 },
        { name: "Speed", value: 80 },
    ],
    description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    abilities: ["Overgrow", "Chlorophyll"],
    appearance: "A large flower on its back is said to take on vivid colors if it gets plenty of nutrition and sunlight.",
    diet: "It is able to convert sunlight into energy, but still enjoys eating fruits.",
    image2d: "venusaur",
    previousEvolution: { id: 2, name: "Ivysaur" },
  },
  {
    id: 4,
    name: "Charmander",
    types: ["Fire"],
    stats: [
      { name: "HP", value: 39 },
      { name: "Attack", value: 52 },
      { name: "Defense", value: 43 },
      { name: "Sp. Atk", value: 60 },
      { name: "Sp. Def", value: 50 },
      { name: "Speed", value: 65 },
    ],
    description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    abilities: ["Blaze", "Solar Power"],
    appearance: "Prefers hot, mountainous areas. The flame on its tail indicates its life force.",
    diet: "Primarily carnivorous, hunting small insects and lizards.",
    image2d: "charmander",
    evolutions: [{ id: 5, name: "Charmeleon" }],
  },
  {
    id: 5,
    name: "Charmeleon",
    types: ["Fire"],
    stats: [
        { name: "HP", value: 58 },
        { name: "Attack", value: 64 },
        { name: "Defense", value: 58 },
        { name: "Sp. Atk", value: 80 },
        { name: "Sp. Def", value: 65 },
        { name: "Speed", value: 80 },
    ],
    description: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.",
    abilities: ["Blaze", "Solar Power"],
    appearance: "It is very hot-headed and seeks out opponents. It calms down only when it wins.",
    diet: "It is a more aggressive hunter than Charmander, often tackling larger prey.",
    image2d: "charmeleon",
    previousEvolution: { id: 4, name: "Charmander" },
    evolutions: [{ id: 6, name: "Charizard" }],
  },
  {
    id: 6,
    name: "Charizard",
    types: ["Fire", "Flying"],
    stats: [
        { name: "HP", value: 78 },
        { name: "Attack", value: 84 },
        { name: "Defense", value: 78 },
        { name: "Sp. Atk", value: 109 },
        { name: "Sp. Def", value: 85 },
        { name: "Speed", value: 100 },
    ],
    description: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
    abilities: ["Blaze", "Solar Power"],
    appearance: "It is said that Charizard's fire burns hotter if it has experienced harsh battles.",
    diet: "A powerful predator, it can hunt large animals and even other Pokémon.",
    image2d: "charizard",
    previousEvolution: { id: 5, name: "Charmeleon" },
  },
  {
    id: 7,
    name: "Squirtle",
    types: ["Water"],
    stats: [
      { name: "HP", value: 44 },
      { name: "Attack", value: 48 },
      { name: "Defense", value: 65 },
      { name: "Sp. Atk", value: 50 },
      { name: "Sp. Def", value: 64 },
      { name: "Speed", value: 43 },
    ],
    description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    abilities: ["Torrent", "Rain Dish"],
    appearance: "Commonly found in freshwater ponds and small lakes. Its shell provides excellent protection.",
    diet: "Omnivorous, feeding on algae, small fish, and aquatic plants.",
    image2d: "squirtle",
    evolutions: [{ id: 8, name: "Wartortle" }],
  },
  {
    id: 8,
    name: "Wartortle",
    types: ["Water"],
    stats: [
        { name: "HP", value: 59 },
        { name: "Attack", value: 63 },
        { name: "Defense", value: 80 },
        { name: "Sp. Atk", value: 65 },
        { name: "Sp. Def", value: 80 },
        { name: "Speed", value: 58 },
    ],
    description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.",
    abilities: ["Torrent", "Rain Dish"],
    appearance: "Often found near water. Its large tail is covered with a rich, thick fur that deepens in color with age.",
    diet: "It actively hunts for fish and other small aquatic creatures.",
    image2d: "wartortle",
    previousEvolution: { id: 7, name: "Squirtle" },
    evolutions: [{ id: 9, name: "Blastoise" }],
  },
  {
    id: 9,
    name: "Blastoise",
    types: ["Water"],
    stats: [
        { name: "HP", value: 79 },
        { name: "Attack", value: 83 },
        { name: "Defense", value: 100 },
        { name: "Sp. Atk", value: 85 },
        { name: "Sp. Def", value: 105 },
        { name: "Speed", value: 78 },
    ],
    description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
    abilities: ["Torrent", "Rain Dish"],
    appearance: "The water spouts on its back are incredibly accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.",
    diet: "It is a capable hunter, but its diet is still primarily based on aquatic plants and fish.",
    image2d: "blastoise",
    previousEvolution: { id: 8, name: "Wartortle" },
  },
  {
    id: 25,
    name: "Pikachu",
    types: ["Electric"],
    stats: [
      { name: "HP", value: 35 },
      { name: "Attack", value: 55 },
      { name: "Defense", value: 40 },
      { name: "Sp. Atk", value: 50 },
      { name: "Sp. Def", value: 50 },
      { name: "Speed", value: 90 },
    ],
    description: "It has small electric sacs on both its cheeks. If threatened, it looses electric charges from the sacs.",
    abilities: ["Static", "Lightning Rod"],
    appearance: "Lives in forests. It raises its tail to check its surroundings and is sometimes struck by lightning in this pose.",
    diet: "Feeds on berries, which it roasts with electricity to make them tender.",
    image2d: "pikachu",
    evolutions: [{ id: 26, name: "Raichu" }],
  },
  {
    id: 26,
    name: "Raichu",
    types: ["Electric"],
    stats: [
        { name: "HP", value: 60 },
        { name: "Attack", value: 90 },
        { name: "Defense", value: 55 },
        { name: "Sp. Atk", value: 90 },
        { name: "Sp. Def", value: 80 },
        { name: "Speed", value: 110 },
    ],
    description: "Its long tail serves as a ground to protect itself from its own high-voltage power.",
    abilities: ["Static", "Lightning Rod"],
    appearance: "Its electric charges can reach up to 100,000 volts. Careless contact can cause even an Indian elephant to faint.",
    diet: "It continues to eat berries, but its powerful electricity allows it to cook them instantly.",
    image2d: "raichu",
    previousEvolution: { id: 25, name: "Pikachu" },
  },
  {
    id: 39,
    name: "Jigglypuff",
    types: ["Normal", "Fairy"],
    stats: [
        { name: "HP", value: 115 },
        { name: "Attack", value: 45 },
        { name: "Defense", value: 20 },
        { name: "Sp. Atk", value: 45 },
        { name: "Sp. Def", value: 25 },
        { name: "Speed", value: 20 },
    ],
    description: "When this Pokémon sings, it never pauses to breathe. If it is in a battle against an opponent that does not easily fall asleep, Jigglypuff cannot breathe, endangering its life.",
    abilities: ["Cute Charm", "Competitive"],
    appearance: "Found in grassy fields and meadows. It captivates foes with its large, expressive eyes.",
    diet: "Enjoys eating sweet fruits and Puff-Puffs, a type of Pokémon snack.",
    image2d: "jigglypuff",
    evolutions: [{ id: 40, name: "Wigglytuff" }],
  },
  {
    id: 40,
    name: "Wigglytuff",
    types: ["Normal", "Fairy"],
    stats: [
        { name: "HP", value: 140 },
        { name: "Attack", value: 70 },
        { name: "Defense", value: 45 },
        { name: "Sp. Atk", value: 85 },
        { name: "Sp. Def", value: 50 },
        { name: "Speed", value: 45 },
    ],
    description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
    abilities: ["Cute Charm", "Competitive"],
    appearance: "Its fur is the ultimate in luxury. Sleeping alongside a Wigglytuff is simply divine.",
    diet: "Its diet remains the same, consisting of sweet fruits and snacks.",
    image2d: "wigglytuff",
    previousEvolution: { id: 39, name: "Jigglypuff" },
  },
  {
    id: 52,
    name: "Meowth",
    types: ["Normal"],
    stats: [
        { name: "HP", value: 40 },
        { name: "Attack", value: 45 },
        { name: "Defense", value: 35 },
        { name: "Sp. Atk", value: 40 },
        { name: "Sp. Def", value: 40 },
        { name: "Speed", value: 90 },
    ],
    description: "It loves to collect shiny things. If it's in a good mood, it might even let its Trainer have a look at its hoard of treasures.",
    abilities: ["Pickup", "Technician"],
    appearance: "A nocturnal Pokémon that is often found in urban environments. It is drawn to shiny objects.",
    diet: "An opportunistic omnivore, eating anything from scraps to small Pokémon.",
    image2d: "meowth",
    evolutions: [{ id: 53, name: "Persian" }],
  },
  {
    id: 53,
    name: "Persian",
    types: ["Normal"],
    stats: [
        { name: "HP", value: 65 },
        { name: "Attack", value: 70 },
        { name: "Defense", value: 60 },
        { name: "Sp. Atk", value: 65 },
        { name: "Sp. Def", value: 65 },
        { name: "Speed", value: 115 },
    ],
    description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
    abilities: ["Limber", "Technician"],
    appearance: "A very proud Pokémon, it will scratch anyone, including its Trainer, for little to no reason.",
    diet: "It is a much more refined hunter than Meowth, stalking prey with grace and stealth.",
    image2d: "persian",
    previousEvolution: { id: 52, name: "Meowth" },
  },
  {
    id: 54,
    name: "Psyduck",
    types: ["Water"],
    stats: [
        { name: "HP", value: 50 },
        { name: "Attack", value: 52 },
        { name: "Defense", value: 48 },
        { name: "Sp. Atk", value: 65 },
        { name: "Sp. Def", value: 50 },
        { name: "Speed", value: 55 },
    ],
    description: "Psyduck uses a mysterious power. When its headache grows intense, it unleashes psychic powers.",
    abilities: ["Damp", "Cloud Nine"],
    appearance: "Lives in freshwater lakes and rivers. Is constantly afflicted by a headache.",
    diet: "Forages for fish and edible plants near the water's edge.",
    image2d: "psyduck",
    evolutions: [{ id: 55, name: "Golduck" }],
  },
  {
    id: 55,
    name: "Golduck",
    types: ["Water"],
    stats: [
        { name: "HP", value: 80 },
        { name: "Attack", value: 82 },
        { name: "Defense", value: 78 },
        { name: "Sp. Atk", value: 95 },
        { name: "Sp. Def", value: 80 },
        { name: "Speed", value: 85 },
    ],
    description: "Often seen swimming elegantly by lakeshores. It is often mistaken for the Japanese monster, Kappa.",
    abilities: ["Damp", "Cloud Nine"],
    appearance: "This Pokémon is a faster swimmer than any human champion. It is found in lakes and rivers.",
    diet: "A skilled swimmer, it preys on fish Pokémon in rivers and lakes.",
    image2d: "golduck",
    previousEvolution: { id: 54, name: "Psyduck" },
  },
    {
    id: 66,
    name: "Machop",
    types: ["Fighting"],
    stats: [
        { name: "HP", value: 70 },
        { name: "Attack", value: 80 },
        { name: "Defense", value: 50 },
        { name: "Sp. Atk", value: 35 },
        { name: "Sp. Def", value: 35 },
        { name: "Speed", value: 35 },
    ],
    description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
    abilities: ["Guts", "No Guard"],
    appearance: "Found in mountainous regions and caves, where it rigorously trains by lifting boulders.",
    diet: "Requires a high-protein diet to maintain its muscle mass, often eating protein-rich plants and eggs.",
    image2d: "machop",
    evolutions: [{ id: 67, name: "Machoke" }],
  },
  {
    id: 67,
    name: "Machoke",
    types: ["Fighting"],
    stats: [
        { name: "HP", value: 80 },
        { name: "Attack", value: 100 },
        { name: "Defense", value: 70 },
        { name: "Sp. Atk", value: 50 },
        { name: "Sp. Def", value: 60 },
        { name: "Speed", value: 45 },
    ],
    description: "Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.",
    abilities: ["Guts", "No Guard"],
    appearance: "It can be found in the wild, but is more often seen in the company of humans, helping with heavy labor.",
    diet: "Its diet is similar to Machop's, but it requires an even greater caloric intake to fuel its muscles.",
    image2d: "machoke",
    previousEvolution: { id: 66, name: "Machop" },
    evolutions: [{ id: 68, name: "Machamp" }],
  },
  {
    id: 68,
    name: "Machamp",
    types: ["Fighting"],
    stats: [
        { name: "HP", value: 90 },
        { name: "Attack", value: 130 },
        { name: "Defense", value: 80 },
        { name: "Sp. Atk", value: 65 },
        { name: "Sp. Def", value: 85 },
        { name: "Speed", value: 55 },
    ],
    description: "Using its four arms, it can fire off a flurry of punches that are impossible to see.",
    abilities: ["Guts", "No Guard"],
    appearance: "With four arms that react faster than it can think, it can execute many punches at once.",
    diet: "It has a voracious appetite and will eat large quantities of food to maintain its energy.",
    image2d: "machamp",
    previousEvolution: { id: 67, name: "Machoke" },
  },
  {
    id: 74,
    name: "Geodude",
    types: ["Rock", "Ground"],
    stats: [
        { name: "HP", value: 40 },
        { name: "Attack", value: 80 },
        { name: "Defense", value: 100 },
        { name: "Sp. Atk", value: 30 },
        { name: "Sp. Def", value: 30 },
        { name: "Speed", value: 20 },
    ],
    description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
    abilities: ["Rock Head", "Sturdy"],
    appearance: "Commonly seen along mountain trails. It levitates slightly above the ground.",
    diet: "It consumes rocks and minerals, showing a preference for rocks covered in moss.",
    image2d: "geodude",
    evolutions: [{ id: 75, name: "Graveler" }],
  },
  {
    id: 75,
    name: "Graveler",
    types: ["Rock", "Ground"],
    stats: [
        { name: "HP", value: 55 },
        { name: "Attack", value: 95 },
        { name: "Defense", value: 115 },
        { name: "Sp. Atk", value: 45 },
        { name: "Sp. Def", value: 45 },
        { name: "Speed", value: 35 },
    ],
    description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
    abilities: ["Rock Head", "Sturdy"],
    appearance: "Lives on mountains. It has a tendency to roll down mountainsides, causing rockslides.",
    diet: "It eats rocks, preferring those with plenty of moss and lichen.",
    image2d: "graveler",
    previousEvolution: { id: 74, name: "Geodude" },
    evolutions: [{ id: 76, name: "Golem" }],
  },
  {
    id: 76,
    name: "Golem",
    types: ["Rock", "Ground"],
    stats: [
        { name: "HP", value: 80 },
        { name: "Attack", value: 120 },
        { name: "Defense", value: 130 },
        { name: "Sp. Atk", value: 55 },
        { name: "Sp. Def", value: 65 },
        { name: "Speed", value: 45 },
    ],
    description: "It is said to live in volcanic craters. It sheds its skin once a year to grow larger.",
    abilities: ["Rock Head", "Sturdy"],
    appearance: "Its boulder-like body is extremely hard. It is capable of withstanding powerful blasts without taking damage.",
    diet: "It feeds on minerals, sometimes venturing into towns to lick the walls of houses.",
    image2d: "golem",
    previousEvolution: { id: 75, name: "Graveler" },
  },
  {
    id: 81,
    name: "Magnemite",
    types: ["Electric", "Steel"],
    stats: [
        { name: "HP", value: 25 },
        { name: "Attack", value: 35 },
        { name: "Defense", value: 70 },
        { name: "Sp. Atk", value: 95 },
        { name: "Sp. Def", value: 55 },
        { name: "Speed", value: 45 },
    ],
    description: "The units at its sides are powerful magnets. They generate a force that repels gravity, allowing it to float.",
    abilities: ["Magnet Pull", "Sturdy"],
    appearance: "Often found near power plants and other areas with strong magnetic fields. They are known to cause blackouts.",
    diet: "Feeds on electricity. It can be found attached to power lines, draining energy.",
    image2d: "magnemite",
    evolutions: [{ id: 82, name: "Magneton" }],
  },
  {
    id: 82,
    name: "Magneton",
    types: ["Electric", "Steel"],
    stats: [
        { name: "HP", value: 50 },
        { name: "Attack", value: 60 },
        { name: "Defense", value: 95 },
        { name: "Sp. Atk", value: 120 },
        { name: "Sp. Def", value: 70 },
        { name: "Speed", value: 70 },
    ],
    description: "Formed by several Magnemite linking together. They are thought to be linked by a strong magnetic force.",
    abilities: ["Magnet Pull", "Sturdy"],
    appearance: "Generates a powerful magnetic field that can damage electronic equipment. They often appear in swarms.",
    diet: "It continues to feed on electricity, often in greater quantities than Magnemite.",
    image2d: "magneton",
    previousEvolution: { id: 81, name: "Magnemite" },
  },
  {
    id: 94,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    stats: [
      { name: "HP", value: 60 },
      { name: "Attack", value: 65 },
      { name: "Defense", value: 60 },
      { name: "Sp. Atk", value: 130 },
      { name: "Sp. Def", value: 75 },
      { name: "Speed", value: 110 },
    ],
    description: "On a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
    abilities: ["Cursed Body"],
    appearance: "Hides in the shadows of rooms, corners, and dark alleys. It is said that Gengar is the cause of any sudden chills.",
    diet: "It is said to steal the life force of its victims. It does not eat in a conventional sense.",
    image2d: "gengar",
  },
  {
    id: 133,
    name: "Eevee",
    types: ["Normal"],
    stats: [
      { name: "HP", value: 55 },
      { name: "Attack", value: 55 },
      { name: "Defense", value: 50 },
      { name: "Sp. Atk", value: 45 },
      { name: "Sp. Def", value: 65 },
      { name: "Speed", value: 55 },
    ],
    description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.",
    abilities: ["Run Away", "Adaptability"],
    appearance: "Rarely found in the wild, most Eevee live in cities and towns with their trainers. Its unstable genetics allow it to evolve in many different ways.",
    diet: "A simple diet of Pokémon food and berries. Its diet can influence its evolutionary path.",
    image2d: "eevee",
    evolutions: [
      { id: 134, name: "Vaporeon" },
      { id: 135, name: "Jolteon" },
      { id: 136, name: "Flareon" },
    ],
  },
   {
    id: 134,
    name: "Vaporeon",
    types: ["Water"],
    stats: [
      { name: "HP", value: 130 }, { name: "Attack", value: 65 }, { name: "Defense", value: 60 },
      { name: "Sp. Atk", value: 110 }, { name: "Sp. Def", value: 95 }, { name: "Speed", value: 65 }
    ],
    description: "Its cell structure is similar to water molecules. It will melt away and become invisible in water.",
    abilities: ["Water Absorb", "Hydration"],
    appearance: "Lives near clean water. Its body is capable of melting into water, making it difficult to spot.",
    diet: "Absorbs water into its body. It can also hunt for fish.",
    image2d: "vaporeon",
    previousEvolution: { id: 133, name: "Eevee" },
  },
  {
    id: 135,
    name: "Jolteon",
    types: ["Electric"],
    stats: [
      { name: "HP", value: 65 }, { name: "Attack", value: 65 }, { name: "Defense", value: 60 },
      { name: "Sp. Atk", value: 110 }, { name: "Sp. Def", value: 95 }, { name: "Speed", value: 130 }
    ],
    description: "It accumulates negative ions from the atmosphere to blast out 10,000-volt lightning bolts.",
    abilities: ["Volt Absorb", "Quick Feet"],
    appearance: "Its fur is made of electrically charged needles. It can bristle its fur to attack.",
    diet: "It generates its own electricity, but it may also absorb static electricity from the air.",
    image2d: "jolteon",
    previousEvolution: { id: 133, name: "Eevee" },
  },
  {
    id: 136,
    name: "Flareon",
    types: ["Fire"],
    stats: [
      { name: "HP", value: 65 }, { name: "Attack", value: 130 }, { name: "Defense", value: 60 },
      { name: "Sp. Atk", value: 95 }, { name: "Sp. Def", value: 110 }, { name: "Speed", value: 65 }
    ],
    description: "It has a flame sac in its body. Its body temperature can reach up to 1,650 degrees Fahrenheit.",
    abilities: ["Flash Fire", "Guts"],
    appearance: "Its fluffy fur has a functional purpose—it releases heat into the air so that its body does not get excessively hot.",
    diet: "It has a fiery nature and enjoys eating spicy foods.",
    image2d: "flareon",
    previousEvolution: { id: 133, name: "Eevee" },
  },
  {
    id: 143,
    name: "Snorlax",
    types: ["Normal"],
    stats: [
      { name: "HP", value: 160 },
      { name: "Attack", value: 110 },
      { name: "Defense", value: 65 },
      { name: "Sp. Atk", value: 65 },
      { name: "Sp. Def", value: 110 },
      { name: "Speed", value: 30 },
    ],
    description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
    abilities: ["Immunity", "Thick Fat"],
    appearance: "Often found sleeping in inconvenient locations like roads and rivers. It only wakes up to eat.",
    diet: "Will eat anything. Its stomach can digest even moldy or rotten food without issue. It needs to eat 900 lbs. of food per day.",
    image2d: "snorlax",
  },
  {
    id: 149,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    stats: [
      { name: "HP", value: 91 },
      { name: "Attack", value: 134 },
      { name: "Defense", value: 95 },
      { name: "Sp. Atk", value: 100 },
      { name: "Sp. Def", value: 100 },
      { name: "Speed", value: 80 },
    ],
    description: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.",
    abilities: ["Inner Focus", "Multiscale"],
    appearance: "Said to live in the sea. It is a kindhearted Pokémon that leads lost ships to safety.",
    diet: "Omnivorous, but has a strong preference for rare, sweet-tasting berries.",
    image2d: "dragonite",
  },
  {
    id: 150,
    name: "Mewtwo",
    types: ["Psychic"],
    stats: [
      { name: "HP", value: 106 },
      { name: "Attack", value: 110 },
      { name: "Defense", value: 90 },
      { name: "Sp. Atk", value: 154 },
      { name: "Sp. Def", value: 90 },
      { name: "Speed", value: 130 },
    ],
    description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
    abilities: ["Pressure", "Unnerve"],
    appearance: "A genetically engineered Pokémon, it was designed to be the ultimate fighting machine. It rests in dark caves, conserving its energy for battle.",
    diet: "Does not need to eat, as it was created to sustain itself on psychic energy.",
    image2d: "mewtwo",
  },
];
