import type { Pokemon, PokemonType } from "./types";

export const ALL_POKEMON_TYPES: PokemonType[] = [
  "Normal", "Fire", "Water", "Grass", "Electric", "Ice", "Fighting", "Poison",
  "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark",
  "Steel", "Fairy"
];

export const allPokemon: Pokemon[] = [
  {
    id: 1,
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    stats: [
      { name: "HP", value: 45 },
      { name: "Attack", value: 49 },
      { name: "Defense", value: 49 },
      { name: "Sp. Atk", value: 65 },
      { name: "Sp. Def", value: 65 },
      { name: "Speed", value: 45 },
    ],
    description: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    abilities: ["Overgrow", "Chlorophyll"],
    appearance: "Found in sunny grasslands and forests. It is often one of the first Pokémon given to new trainers in the Kanto region.",
    diet: "It absorbs nutrients from the seed on its back, but also eats small insects and berries.",
    image2d: "bulbasaur",
  },
  {
    id: 4,
    name: "Charmander",
    types: ["Fire"],
    stats: [
      { name: "HP", value: 39 },
      { name: "Attack", value: 52 },
      { name: "Defense", value: 43 },
      { name: "Sp. Atk", value: 60 },
      { name: "Sp. Def", value: 50 },
      { name: "Speed", value: 65 },
    ],
    description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    abilities: ["Blaze", "Solar Power"],
    appearance: "Prefers hot, mountainous areas. The flame on its tail indicates its life force.",
    diet: "Primarily carnivorous, hunting small insects and lizards.",
    image2d: "charmander",
  },
  {
    id: 7,
    name: "Squirtle",
    types: ["Water"],
    stats: [
      { name: "HP", value: 44 },
      { name: "Attack", value: 48 },
      { name: "Defense", value: 65 },
      { name: "Sp. Atk", value: 50 },
      { name: "Sp. Def", value: 64 },
      { name: "Speed", value: 43 },
    ],
    description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    abilities: ["Torrent", "Rain Dish"],
    appearance: "Commonly found in freshwater ponds and small lakes. Its shell provides excellent protection.",
    diet: "Omnivorous, feeding on algae, small fish, and aquatic plants.",
    image2d: "squirtle",
  },
  {
    id: 25,
    name: "Pikachu",
    types: ["Electric"],
    stats: [
      { name: "HP", value: 35 },
      { name: "Attack", value: 55 },
      { name: "Defense", value: 40 },
      { name: "Sp. Atk", value: 50 },
      { name: "Sp. Def", value: 50 },
      { name: "Speed", value: 90 },
    ],
    description: "It has small electric sacs on both its cheeks. If threatened, it looses electric charges from the sacs.",
    abilities: ["Static", "Lightning Rod"],
    appearance: "Lives in forests. It raises its tail to check its surroundings and is sometimes struck by lightning in this pose.",
    diet: "Feeds on berries, which it roasts with electricity to make them tender.",
    image2d: "pikachu",
  },
  {
    id: 39,
    name: "Jigglypuff",
    types: ["Normal", "Fairy"],
    stats: [
        { name: "HP", value: 115 },
        { name: "Attack", value: 45 },
        { name: "Defense", value: 20 },
        { name: "Sp. Atk", value: 45 },
        { name: "Sp. Def", value: 25 },
        { name: "Speed", value: 20 },
    ],
    description: "When this Pokémon sings, it never pauses to breathe. If it is in a battle against an opponent that does not easily fall asleep, Jigglypuff cannot breathe, endangering its life.",
    abilities: ["Cute Charm", "Competitive"],
    appearance: "Found in grassy fields and meadows. It captivates foes with its large, expressive eyes.",
    diet: "Enjoys eating sweet fruits and Puff-Puffs, a type of Pokémon snack.",
    image2d: "jigglypuff",
  },
  {
    id: 52,
    name: "Meowth",
    types: ["Normal"],
    stats: [
        { name: "HP", value: 40 },
        { name: "Attack", value: 45 },
        { name: "Defense", value: 35 },
        { name: "Sp. Atk", value: 40 },
        { name: "Sp. Def", value: 40 },
        { name: "Speed", value: 90 },
    ],
    description: "It loves to collect shiny things. If it's in a good mood, it might even let its Trainer have a look at its hoard of treasures.",
    abilities: ["Pickup", "Technician"],
    appearance: "A nocturnal Pokémon that is often found in urban environments. It is drawn to shiny objects.",
    diet: "An opportunistic omnivore, eating anything from scraps to small Pokémon.",
    image2d: "meowth",
  },
  {
    id: 54,
    name: "Psyduck",
    types: ["Water"],
    stats: [
        { name: "HP", value: 50 },
        { name: "Attack", value: 52 },
        { name: "Defense", value: 48 },
        { name: "Sp. Atk", value: 65 },
        { name: "Sp. Def", value: 50 },
        { name: "Speed", value: 55 },
    ],
    description: "Psyduck uses a mysterious power. When its headache grows intense, it unleashes psychic powers.",
    abilities: ["Damp", "Cloud Nine"],
    appearance: "Lives in freshwater lakes and rivers. Is constantly afflicted by a headache.",
    diet: "Forages for fish and edible plants near the water's edge.",
    image2d: "psyduck",
  },
    {
    id: 66,
    name: "Machop",
    types: ["Fighting"],
    stats: [
        { name: "HP", value: 70 },
        { name: "Attack", value: 80 },
        { name: "Defense", value: 50 },
        { name: "Sp. Atk", value: 35 },
        { name: "Sp. Def", value: 35 },
        { name: "Speed", value: 35 },
    ],
    description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
    abilities: ["Guts", "No Guard"],
    appearance: "Found in mountainous regions and caves, where it rigorously trains by lifting boulders.",
    diet: "Requires a high-protein diet to maintain its muscle mass, often eating protein-rich plants and eggs.",
    image2d: "machop",
  },
  {
    id: 74,
    name: "Geodude",
    types: ["Rock", "Ground"],
    stats: [
        { name: "HP", value: 40 },
        { name: "Attack", value: 80 },
        { name: "Defense", value: 100 },
        { name: "Sp. Atk", value: 30 },
        { name: "Sp. Def", value: 30 },
        { name: "Speed", value: 20 },
    ],
    description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
    abilities: ["Rock Head", "Sturdy"],
    appearance: "Commonly seen along mountain trails. It levitates slightly above the ground.",
    diet: "It consumes rocks and minerals, showing a preference for rocks covered in moss.",
    image2d: "geodude",
  },
  {
    id: 81,
    name: "Magnemite",
    types: ["Electric", "Steel"],
    stats: [
        { name: "HP", value: 25 },
        { name: "Attack", value: 35 },
        { name: "Defense", value: 70 },
        { name: "Sp. Atk", value: 95 },
        { name: "Sp. Def", value: 55 },
        { name: "Speed", value: 45 },
    ],
    description: "The units at its sides are powerful magnets. They generate a force that repels gravity, allowing it to float.",
    abilities: ["Magnet Pull", "Sturdy"],
    appearance: "Often found near power plants and other areas with strong magnetic fields. They are known to cause blackouts.",
    diet: "Feeds on electricity. It can be found attached to power lines, draining energy.",
    image2d: "magnemite",
  },
  {
    id: 94,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    stats: [
      { name: "HP", value: 60 },
      { name: "Attack", value: 65 },
      { name: "Defense", value: 60 },
      { name: "Sp. Atk", value: 130 },
      { name: "Sp. Def", value: 75 },
      { name: "Speed", value: 110 },
    ],
    description: "On a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
    abilities: ["Cursed Body"],
    appearance: "Hides in the shadows of rooms, corners, and dark alleys. It is said that Gengar is the cause of any sudden chills.",
    diet: "It is said to steal the life force of its victims. It does not eat in a conventional sense.",
    image2d: "gengar",
  },
  {
    id: 133,
    name: "Eevee",
    types: ["Normal"],
    stats: [
      { name: "HP", value: 55 },
      { name: "Attack", value: 55 },
      { name: "Defense", value: 50 },
      { name: "Sp. Atk", value: 45 },
      { name: "Sp. Def", value: 65 },
      { name: "Speed", value: 55 },
    ],
    description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.",
    abilities: ["Run Away", "Adaptability"],
    appearance: "Rarely found in the wild, most Eevee live in cities and towns with their trainers. Its unstable genetics allow it to evolve in many different ways.",
    diet: "A simple diet of Pokémon food and berries. Its diet can influence its evolutionary path.",
    image2d: "eevee",
  },
  {
    id: 143,
    name: "Snorlax",
    types: ["Normal"],
    stats: [
      { name: "HP", value: 160 },
      { name: "Attack", value: 110 },
      { name: "Defense", value: 65 },
      { name: "Sp. Atk", value: 65 },
      { name: "Sp. Def", value: 110 },
      { name: "Speed", value: 30 },
    ],
    description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
    abilities: ["Immunity", "Thick Fat"],
    appearance: "Often found sleeping in inconvenient locations like roads and rivers. It only wakes up to eat.",
    diet: "Will eat anything. Its stomach can digest even moldy or rotten food without issue. It needs to eat 900 lbs. of food per day.",
    image2d: "snorlax",
  },
  {
    id: 149,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    stats: [
      { name: "HP", value: 91 },
      { name: "Attack", value: 134 },
      { name: "Defense", value: 95 },
      { name: "Sp. Atk", value: 100 },
      { name: "Sp. Def", value: 100 },
      { name: "Speed", value: 80 },
    ],
    description: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.",
    abilities: ["Inner Focus", "Multiscale"],
    appearance: "Said to live in the sea. It is a kindhearted Pokémon that leads lost ships to safety.",
    diet: "Omnivorous, but has a strong preference for rare, sweet-tasting berries.",
    image2d: "dragonite",
  },
  {
    id: 150,
    name: "Mewtwo",
    types: ["Psychic"],
    stats: [
      { name: "HP", value: 106 },
      { name: "Attack", value: 110 },
      { name: "Defense", value: 90 },
      { name: "Sp. Atk", value: 154 },
      { name: "Sp. Def", value: 90 },
      { name: "Speed", value: 130 },
    ],
    description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
    abilities: ["Pressure", "Unnerve"],
    appearance: "A genetically engineered Pokémon, it was designed to be the ultimate fighting machine. It rests in dark caves, conserving its energy for battle.",
    diet: "Does not need to eat, as it was created to sustain itself on psychic energy.",
    image2d: "mewtwo",
  },
];
